/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as legalRouteRouteImport } from './routes/(legal)/route'
import { Route as featuresRouteRouteImport } from './routes/(features)/route'
import { Route as featuresIndexRouteImport } from './routes/(features)/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as legalTermsOfServiceRouteImport } from './routes/(legal)/terms-of-service'
import { Route as legalPrivacyPolicyRouteImport } from './routes/(legal)/privacy-policy'
import { Route as featuresWardrobeRouteImport } from './routes/(features)/wardrobe'
import { Route as featuresOutfitsRouteImport } from './routes/(features)/outfits'
import { Route as featuresFavoritesRouteImport } from './routes/(features)/favorites'

const legalRouteRoute = legalRouteRouteImport.update({
  id: '/(legal)',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresRouteRoute = featuresRouteRouteImport.update({
  id: '/(features)',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresIndexRoute = featuresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => featuresRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const legalTermsOfServiceRoute = legalTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => legalRouteRoute,
} as any)
const legalPrivacyPolicyRoute = legalPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => legalRouteRoute,
} as any)
const featuresWardrobeRoute = featuresWardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => featuresRouteRoute,
} as any)
const featuresOutfitsRoute = featuresOutfitsRouteImport.update({
  id: '/outfits',
  path: '/outfits',
  getParentRoute: () => featuresRouteRoute,
} as any)
const featuresFavoritesRoute = featuresFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => featuresRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/favorites': typeof featuresFavoritesRoute
  '/outfits': typeof featuresOutfitsRoute
  '/wardrobe': typeof featuresWardrobeRoute
  '/privacy-policy': typeof legalPrivacyPolicyRoute
  '/terms-of-service': typeof legalTermsOfServiceRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof featuresIndexRoute
}
export interface FileRoutesByTo {
  '/favorites': typeof featuresFavoritesRoute
  '/outfits': typeof featuresOutfitsRoute
  '/wardrobe': typeof featuresWardrobeRoute
  '/privacy-policy': typeof legalPrivacyPolicyRoute
  '/terms-of-service': typeof legalTermsOfServiceRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof featuresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(features)': typeof featuresRouteRouteWithChildren
  '/(legal)': typeof legalRouteRouteWithChildren
  '/(features)/favorites': typeof featuresFavoritesRoute
  '/(features)/outfits': typeof featuresOutfitsRoute
  '/(features)/wardrobe': typeof featuresWardrobeRoute
  '/(legal)/privacy-policy': typeof legalPrivacyPolicyRoute
  '/(legal)/terms-of-service': typeof legalTermsOfServiceRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/(features)/': typeof featuresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/favorites'
    | '/outfits'
    | '/wardrobe'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/sign-in'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/favorites'
    | '/outfits'
    | '/wardrobe'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/sign-in'
    | '/'
  id:
    | '__root__'
    | '/(features)'
    | '/(legal)'
    | '/(features)/favorites'
    | '/(features)/outfits'
    | '/(features)/wardrobe'
    | '/(legal)/privacy-policy'
    | '/(legal)/terms-of-service'
    | '/auth/sign-in'
    | '/(features)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  featuresRouteRoute: typeof featuresRouteRouteWithChildren
  legalRouteRoute: typeof legalRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(legal)': {
      id: '/(legal)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof legalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)': {
      id: '/(features)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof featuresRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/': {
      id: '/(features)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof featuresIndexRouteImport
      parentRoute: typeof featuresRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/terms-of-service': {
      id: '/(legal)/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof legalTermsOfServiceRouteImport
      parentRoute: typeof legalRouteRoute
    }
    '/(legal)/privacy-policy': {
      id: '/(legal)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof legalPrivacyPolicyRouteImport
      parentRoute: typeof legalRouteRoute
    }
    '/(features)/wardrobe': {
      id: '/(features)/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof featuresWardrobeRouteImport
      parentRoute: typeof featuresRouteRoute
    }
    '/(features)/outfits': {
      id: '/(features)/outfits'
      path: '/outfits'
      fullPath: '/outfits'
      preLoaderRoute: typeof featuresOutfitsRouteImport
      parentRoute: typeof featuresRouteRoute
    }
    '/(features)/favorites': {
      id: '/(features)/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof featuresFavoritesRouteImport
      parentRoute: typeof featuresRouteRoute
    }
  }
}

interface featuresRouteRouteChildren {
  featuresFavoritesRoute: typeof featuresFavoritesRoute
  featuresOutfitsRoute: typeof featuresOutfitsRoute
  featuresWardrobeRoute: typeof featuresWardrobeRoute
  featuresIndexRoute: typeof featuresIndexRoute
}

const featuresRouteRouteChildren: featuresRouteRouteChildren = {
  featuresFavoritesRoute: featuresFavoritesRoute,
  featuresOutfitsRoute: featuresOutfitsRoute,
  featuresWardrobeRoute: featuresWardrobeRoute,
  featuresIndexRoute: featuresIndexRoute,
}

const featuresRouteRouteWithChildren = featuresRouteRoute._addFileChildren(
  featuresRouteRouteChildren,
)

interface legalRouteRouteChildren {
  legalPrivacyPolicyRoute: typeof legalPrivacyPolicyRoute
  legalTermsOfServiceRoute: typeof legalTermsOfServiceRoute
}

const legalRouteRouteChildren: legalRouteRouteChildren = {
  legalPrivacyPolicyRoute: legalPrivacyPolicyRoute,
  legalTermsOfServiceRoute: legalTermsOfServiceRoute,
}

const legalRouteRouteWithChildren = legalRouteRoute._addFileChildren(
  legalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  featuresRouteRoute: featuresRouteRouteWithChildren,
  legalRouteRoute: legalRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
